<a href="https://colab.research.google.com/github/20000109/Exercises-about-Numpy-library/blob/main/Kevin_Tip%C3%A1n_Exercises_about_Numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

aux = np.array([1,2,4,5])
print(aux)
print(aux.shape)
aux = np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
tmp = np.zeros([4,4])
print (tmp)
tmp = np.full([4,4],5)
print (tmp)
tmp = np.eye(4,4)
print (tmp)
tmp = np.ones([4,4])
print (tmp)
print (tmp.shape)
tmp = 10*np.random.random([3,3])
print (tmp)

[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
[[8.72353022 8.48055555 5.07888002]
 [9.23173535 0.56365013 3.07645065]
 [2.93583318 4.38124842 1.0202041 ]]


In [ ]:
tmp = 10*np.random.random([3,3])
print (tmp)

[[2.4762185  0.56987862 2.07195311]
 [5.37325717 6.92609307 5.61517262]
 [3.76360205 0.2113081  9.51459267]]


In [ ]:
print (tmp[:2,:2])

[[2.4762185  0.56987862]
 [5.37325717 6.92609307]]


In [ ]:
print (tmp[:2,1:3])

[[0.56987862 2.07195311]
 [6.92609307 5.61517262]]


In [ ]:
print (tmp [2,2])

9.514592669718619


Filtrar valores con mask

In [ ]:
mask = tmp>5
print (tmp[mask])

[5.37325717 6.92609307 5.61517262 9.51459267]


In [ ]:
mask = (tmp>=2) & (tmp<=4)
print (tmp[mask])

[2.4762185  2.07195311 3.76360205]


In [ ]:
tmp = np.random.randint(0,10,[4,4])
print (tmp)

[[5 5 4 2]
 [0 2 7 1]
 [1 4 3 2]
 [1 0 8 0]]


Extraer numeros pares

In [ ]:
nrosEnteros = np.random.randint(0, 10, size=(4, 4))
print(nrosEnteros)


print('---------------------------')
nrosEnteros = nrosEnteros[nrosEnteros % 2 == 0]
print(nrosEnteros)


[[5 1 9 7]
 [3 0 8 8]
 [2 9 1 1]
 [5 6 3 5]]
---------------------------
[0 8 8 2 6]


In [1]:
from numpy.random import MT19937
import numpy as np
print ("Matriz 1")
m1 = np.random.randint(1,11,[3,4])
print (m1)
print (m1.shape)
print ("Matriz 2")
m2 = np.random.randint(1,11,[3,4])
print (m2)
print (m2.shape)
print ("Suma de matrices")
print (m1 + m2)
print ("Resta de matrices")
print (m1 - m2)
print ("Multiplicacion de matrices")
print (m1 * m2)

Matriz 1
[[ 1  5  8  5]
 [ 3  7 10  5]
 [10 10  3  7]]
(3, 4)
Matriz 2
[[5 7 3 2]
 [2 8 2 9]
 [3 3 6 5]]
(3, 4)
Suma de matrices
[[ 6 12 11  7]
 [ 5 15 12 14]
 [13 13  9 12]]
Resta de matrices
[[-4 -2  5  3]
 [ 1 -1  8 -4]
 [ 7  7 -3  2]]
Multiplicacion de matrices
[[ 5 35 24 10]
 [ 6 56 20 45]
 [30 30 18 35]]


In [2]:
print ("Suma de matrices")
print (np.add(m1,m2))
print ("Resta de matrices")
print (np.subtract(m1,m2))
print ("Multiplicacion de matrices")
print (np.multiply(m1,m2))
print ("Division de matrices")
print (np.divide(m1,m2))

Suma de matrices
[[ 6 12 11  7]
 [ 5 15 12 14]
 [13 13  9 12]]
Resta de matrices
[[-4 -2  5  3]
 [ 1 -1  8 -4]
 [ 7  7 -3  2]]
Multiplicacion de matrices
[[ 5 35 24 10]
 [ 6 56 20 45]
 [30 30 18 35]]
Division de matrices
[[0.2        0.71428571 2.66666667 2.5       ]
 [1.5        0.875      5.         0.55555556]
 [3.33333333 3.33333333 0.5        1.4       ]]


In [3]:
print ("Matriz 1")
m3 = np.random.randint(1,11,[3,4])
print (m3)
print (m3.shape)
print ("Matriz 2")
m4 = np.random.randint(1,11,[4,3])
print (m4)
print (m4.shape)

print (np.dot(m3,m4))

Matriz 1
[[10  1  2  9]
 [ 5  3  7  5]
 [10  9  2  9]]
(3, 4)
Matriz 2
[[1 1 6]
 [9 6 2]
 [8 9 1]
 [8 1 2]]
(4, 3)
[[107  43  82]
 [128  91  53]
 [179  91  98]]


In [4]:
print ("Matriz 1")
m5 = np.random.randint(1,11,[2,2])
print (m5.shape)
print (type (m5))
print (m5)
print (m5.T)

Matriz 1
(2, 2)
<class 'numpy.ndarray'>
[[4 3]
 [1 3]]
[[4 1]
 [3 3]]


In [5]:
print ("Matriz 1")
m6 = np.random.randint(1,11,[4,3])
m7 = np.array([1,0,2])
print (m6.shape)
print (m7.shape)
m8 = np.empty_like(m6)
print (m6)
print (m7)
print (m8.shape)
print (m8)

Matriz 1
(4, 3)
(3,)
[[ 7  5 10]
 [ 7  9  2]
 [ 9  9 10]
 [ 5  9  5]]
[1 0 2]
(4, 3)
[[4596373779694328218 4604608933298662839 4613187218303178069]
 [4612811918334230528 4609434218613702656 4606056518893174784]
 [4617315517961601024 4603179219131243634 4614688418178968235]
 [4614688418178968235 4602678819172646912 4608983858650965606]]


In [6]:
for i in range(4):
  m8[i,:]= m6[i,:]+m7
print (m6)
print (m7)
print (m8)

[[ 7  5 10]
 [ 7  9  2]
 [ 9  9 10]
 [ 5  9  5]]
[1 0 2]
[[ 8  5 12]
 [ 8  9  4]
 [10  9 12]
 [ 6  9  7]]


In [7]:
a = np.array([1,2,3])
print (a)
b = np.tile(a,(6,1))
print (b)
print (b.shape)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(6, 3)


In [8]:
m1 = np.random.randint(20,30,[6,6])
print (m1)

[[26 23 25 24 21 20]
 [22 27 29 20 26 28]
 [28 20 27 26 26 21]
 [21 26 21 25 26 25]
 [29 21 21 26 22 23]
 [24 28 23 24 29 25]]


In [9]:
print('Matriz A')
A = np.array([1,2,3])

print(A)

print(' ')
print('----------------------------------------------------------')
print(' ')

print('Matriz B')
B = np.array([1,2,3])
matriz = np.tile(B, (6, 1))
print(matriz)

print(' ')
print('---------------------------------------------------------')
print(' ')

print('Matriz C')
C = np.random.randint(0, 11, size=(6, 6))
print(C)
promedio = np.mean(C)
print(' ')
print('Promedio')
print(promedio)

print(' ')
print('------------------------------------------------------------')
print(' ')

promedio1 = np.mean(C, axis=1)
print(' ')
print('Promedio por filas')
print(promedio1)

print(' ')
print('-------------------------------------------------------------')
print(' ')

promedio2 = np.mean(C, axis=0)
print(' ')
print('Promedio por columnas')
print(promedio2)

Matriz A
[1 2 3]
 
----------------------------------------------------------
 
Matriz B
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
 
---------------------------------------------------------
 
Matriz C
[[ 1  1  2  4  6  0]
 [ 2  0  5  8  2  1]
 [ 9  5  7  2  5  8]
 [ 8 10  6  2  7  7]
 [ 6  3  5 10  3  6]
 [10  0  1  1  0  4]]
 
Promedio
4.361111111111111
 
------------------------------------------------------------
 
 
Promedio por filas
[2.33333333 3.         6.         6.66666667 5.5        2.66666667]
 
-------------------------------------------------------------
 
 
Promedio por columnas
[6.         3.16666667 4.33333333 4.5        3.83333333 4.33333333]
